INSERT INTO agenda_summaries (id, event_id, agenda_url, agenda_text, summary, content_hash, last_summarized_at)
VALUES (
  '1013c580-cb96-4ca7-bb41-1a142aa3421f',
  'f405994d-773c-40f6-98c7-36c229491eda',
  'https://www.congress.gov/118/bills/hr1/BILLS-118hr1ih.pdf',
  'I 118 TH   CONGRESS 1   ST   S ESSION   H. R. 1  To lower energy costs by increasing American energy production, exports, infrastructure,   and   critical   minerals   processing,   by   promoting   trans- parency,   accountability,   permitting,   and   production   of   American   re- sources, and by improving water quality certification and energy projects, and for other purposes. IN THE HOUSE OF REPRESENTATIVES MARCH   14, 2023 Mr. S CALISE   (for himself, Mrs. R ODGERS   of Washington, Mr. W ESTERMAN   , and Mr. G   RAVES   of Missouri) introduced the following bill; which was re- ferred to the Committee on Natural Resources, and in addition to the Committees on Energy and Commerce, Agriculture, Transportation and Infrastructure, and the Budget, for a period to be subsequently deter- mined by the Speaker, in each case for consideration of such provisions as fall within the jurisdiction of the committee concerned  A BILL  To lower energy costs by increasing American energy produc- tion, exports, infrastructure, and critical minerals proc- essing, by promoting transparency, accountability, per- mitting, and production of American resources, and by improving water quality certification and energy projects, and for other purposes.  Be it enacted by the Senate and House of Representa- 1  tives of the United States of America in Congress assembled, 2  VerDate Sep 11 2014   03:17 Mar 15, 2023   Jkt 039200   PO 00000   Frm 00001   Fmt 6652   Sfmt 6201   E:\BILLS\H1.IH   H1 kjohnson on DSK79L0C42PROD with BILLS
2  • HR 1 IH SECTION 1. SHORT TITLE; TABLE OF CONTENTS. 1  (a) S HORT   T ITLE   .—This Act may be cited as the 2  ‘‘Lower Energy Costs Act’’. 3  (b) T ABLE OF   C ONTENTS   .—The table of contents of 4  this Act is as follows: 5  Sec. 1. Short title; table of contents. DIVISION   A—INCREASING   AMERICAN   ENERGY   PRODUCTION,   EX- PORTS,   INFRASTRUCTURE,   AND   CRITICAL   MINERALS   PROC- ESSING Sec. 10001. Securing America’s critical minerals supply. Sec. 10002. Protecting American energy production. Sec. 10003. Researching Efficient Federal Improvements for Necessary Energy Refining. Sec. 10004. Promoting cross-border energy infrastructure. Sec. 10005. Sense of Congress expressing disapproval of the revocation of the Presidential permit for the Keystone XL pipeline. Sec. 10006. Sense of Congress opposing restrictions on the export of crude oil or other petroleum products. Sec. 10007. Unlocking our domestic LNG potential. Sec. 10008. Promoting interagency coordination for review of natural gas pipe- lines. Sec. 10009. Interim hazardous waste permits for critical energy resource facili- ties. Sec. 10010. Flexible air permits for critical energy resource facilities. Sec. 10011. National security or energy security waivers to produce critical en- ergy resources. Sec. 10012. Ending future delays in chemical substance review for critical en- ergy resources. Sec. 10013. Natural gas tax repeal. Sec. 10014. Repeal of greenhouse gas reduction fund. Sec. 10015. Keeping America’s refineries operating. Sec. 10016. Homeowner energy freedom. DIVISION B—TRANSPARENCY, ACCOUNTABILITY, PERMITTING, AND PRODUCTION OF AMERICAN RESOURCES Sec. 20001. Short title; table of contents. TITLE I—ONSHORE AND OFFSHORE LEASING AND OVERSIGHT Sec. 20101. Onshore oil and gas leasing. Sec. 20102. Lease reinstatement. Sec. 20103. Protested lease sales. Sec. 20104. Suspension of operations. Sec. 20105. Administrative protest process reform. Sec. 20106. Leasing and permitting transparency. Sec. 20107. Offshore oil and gas leasing. Sec. 20108. Five-year plan for offshore oil and gas leasing. Sec. 20109. Geothermal leasing.  VerDate Sep 11 2014   03:17 Mar 15, 2023   Jkt 039200   PO 00000   Frm 00002   Fmt 6652   Sfmt 6211   E:\BILLS\H1.IH   H1 kjohnson on DSK79L0C42PROD with BILLS
3  • HR 1 IH  Sec. 20110. Leasing for certain qualified coal applications. Sec. 20111. Future coal leasing. Sec. 20112. Staff planning report. Sec. 20113. Prohibition on Chinese communist party ownership interest. Sec. 20114. Effect on other law. TITLE II—PERMITTING STREAMLINING Sec. 20201. Definitions. Sec. 20202. BUILDER Act. Sec. 20203. Codification of National Environmental Policy Act regulations. Sec. 20204. Non-major Federal actions. Sec. 20205. No net loss determination for existing rights-of-way. Sec. 20206. Determination of National Environmental Policy Act adequacy. Sec. 20207. Determination regarding rights-of-way. Sec. 20208. Terms of rights-of-way. Sec. 20209. Funding to process permits and develop information technology. Sec. 20210. Offshore geological and geophysical survey licensing. Sec. 20211. Deferral of applications for permits to drill. Sec. 20212. Processing and terms of applications for permits to drill. Sec. 20213. Amendments to the Energy Policy Act of 2005. Sec. 20214. Access to Federal energy resources from non-Federal surface es- tate. Sec. 20215. Scope of environmental reviews for oil and gas leases. Sec. 20216. Expediting approval o',
  'Here’s a 2-3 sentence summary of H.R. 1:

H.R. 1, the “Lower Energy Costs Act,” aims to reduce energy costs in the United States by boosting domestic energy production, exports, and critical minerals processing. The bill focuses on streamlining permitting processes, improving water quality certifications for energy projects, and expanding energy infrastructure. Ultimately, it seeks to strengthen America’s energy security and competitiveness.',
  'a391642c921536a8c2ce8768e58657efe81b40e9cc383f03903cd4bcadbe0478',
  datetime('now')
);